name: Auto-Create & Sync Repository Labels

on:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  sync-labels:
    name: Sync GitHub Issue Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Sync Labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml_file: .github/labels.yml
          skip_delete: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
